site_name: OliDox
site_url: https://iwantlotsofcookies.github.io/OliDox/
theme: 
  font:
    text: Inconsolata
    #text: roberto

  palette:
    #primary: indigo
    #accent: indigo
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
          icon: material/brightness-4
          name: Switch to light mode

  features:
    - navigation.sections
    #- navigation.expand
    #- navigation.tracking
    #- navigation.tabs
    - navigation.indexes
    #- navigation.path
    #- toc.follow
    - toc.integrate
    - search.suggest
    #- search.highlight

  plugins:
    - search
    - optimize

  name: material

extra_css:
 - stylesheets/extra.css
