site_name: OliDox
site_url: https://iwantlotsofcookies.github.io/OliDox/
theme: 
  name: material
  font:
    text: Inconsolata
    #text: roberto

  palette:
        # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: white
      scheme: white
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: black
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - navigation.sections
    #- navigation.expand
    #- navigation.tracking
    - navigation.tabs
    - navigation.indexes
    #- navigation.path
    #- toc.follow
    - toc.integrate
    - search.suggest
    #- search.highlight

  plugins:
    - search
    - optimize
    - git-authors

      


repo_url: https://github.com/iwantlotsofcookies/olidox
repo_name: iwantlotsofcookies/OliDox



extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
